### ISSUE TITLE
no open token

### ISSUE THREAD

**Issue by allelive** [mkdirlove/FBTOOL#39]
Traceback (most recent call last):
  File "fbtool.py", line 2552, in <module>
    tool_main_function()
  File "fbtool.py", line 107, in tool_main_function
    login()
  File "fbtool.py", line 137, in login
    br.form['email'] = id
  File "/home/ale/.local/lib/python2.7/site-packages/mechanize/_form_controls.py", line 1963, in __setitem__
    control = self.find_control(name)
  File "/home/ale/.local/lib/python2.7/site-packages/mechanize/_form_controls.py", line 2355, in find_control
    return self._find_control(name, type, kind, id, label, predicate, nr)
  File "/home/ale/.local/lib/python2.7/site-packages/mechanize/_form_controls.py", line 2448, in _find_control
    raise ControlNotFoundError("no control matching " + description)
mechanize._form_controls.ControlNotFoundError: no control matching name 'email'

**Comment by allelive** [comment]
login correct
