### ISSUE TITLE
AttributeError: 'function' object has no attribute 'append'

### ISSUE THREAD

**Issue by Bubblebug17** [mkdirlove/FBTOOL#6]
When i trying to get a "email friend from friend". I get this python error

**Comment by Bubblebug17** [comment]
Full traceback: 

> Traceback (most recent call last):
  File "fbtool.py", line 2548, in <module>
    tool_main_function()
  File "fbtool.py", line 103, in tool_main_function
    login()
  File "fbtool.py", line 153, in login
    menu()
  File "fbtool.py", line 232, in menu
    choices()
  File "fbtool.py", line 240, in choices
    information()
  File "fbtool.py", line 322, in information
    menu()
  File "fbtool.py", line 232, in menu
    choices()
  File "fbtool.py", line 240, in choices
    information()
  File "fbtool.py", line 328, in information
    menu()
  File "fbtool.py", line 232, in menu
    choices()
  File "fbtool.py", line 248, in choices
    lain()
  File "fbtool.py", line 2282, in lain
    choosing_again()
  File "fbtool.py", line 2294, in choosing_again
    check_akun()
  File "fbtool.py", line 2415, in check_akun
    lain()
  File "fbtool.py", line 2282, in lain
    choosing_again()
  File "fbtool.py", line 2292, in choosing_again
    wordlist()
  File "fbtool.py", line 2386, in wordlist
    lain()
  File "fbtool.py", line 2282, in lain
    choosing_again()
  File "fbtool.py", line 2288, in choosing_again
    choosing_again()
  File "fbtool.py", line 2300, in choosing_again
    menu()
  File "fbtool.py", line 232, in menu
    choices()
  File "fbtool.py", line 244, in choices
    menu_hack()
  File "fbtool.py", line 940, in menu_hack
    choose_hack()
  File "fbtool.py", line 948, in choose_hack
    mini()
  File "fbtool.py", line 1135, in mini
    menu_hack()
  File "fbtool.py", line 940, in menu_hack
    choose_hack()
  File "fbtool.py", line 950, in choose_hack
    crack()
  File "fbtool.py", line 1170, in crack
    menu_hack()
  File "fbtool.py", line 940, in menu_hack
    choose_hack()
  File "fbtool.py", line 953, in choose_hack
    super()
  File "fbtool.py", line 1243, in super
    choices_super()
  File "fbtool.py", line 1472, in choices_super
    super()
  File "fbtool.py", line 1243, in super
    choices_super()
  File "fbtool.py", line 1249, in choices_super
    choices_super()
  File "fbtool.py", line 1304, in choices_super
    menu_hack()
  File "fbtool.py", line 940, in menu_hack
    choose_hack()
  File "fbtool.py", line 959, in choose_hack
    menu()
  File "fbtool.py", line 232, in menu
    choices()
  File "fbtool.py", line 242, in choices
    dump()
  File "fbtool.py", line 353, in dump
    choose_dump()
  File "fbtool.py", line 377, in choose_dump
    phone_number_from_friends()
  File "fbtool.py", line 912, in phone_number_from_friends
    dump()
  File "fbtool.py", line 353, in dump
    choose_dump()
  File "fbtool.py", line 373, in choose_dump
    email_from_friends()
  File "fbtool.py", line 769, in email_from_friends
    email_from_friends.append(z['email'])
